version: "3.8"
services:
  display:
    build: "./display"
    restart: unless-stopped
    ports:
      - "80:${DISPLAY_PORT}"
    environments:
      - SERVER_IP=127.0.0.1
      - DISPLAY_PORT=${SERVER_PORT}

    pinger:
      build: "./pinger"
      restart: unless-stopped
      ports:
        - "${SERVER_PORT}:${SERVER_PORT}"
      environments:
        - HOST=1.1.1.1
        - PORT=${SERVER_PORT},
        - INTERVAL=1000
        - PING_AMOUNT_FOR_AVERAGE=20
