version: "3.8"
services:
  display:
    build: "./display"
    restart: unless-stopped
    ports:
      - ${DISPLAY_PORT}:80
    environment:
      - VITE_SERVER_URI=${SERVER_URI}

  pinger:
    build: "./pinger"
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:2323
    environment:
      - HOST=1.1.1.1
      - INTERVAL=1000
      - PING_AMOUNT_FOR_AVERAGE=20
