FROM node:16.14.0-alpine3.15 as builder

ARG server_uri=ws://127.0.0.1:2324
ENV VITE_SERVER_URI=$server_uri

WORKDIR /app
RUN chown node:node ./
USER node

COPY package.json package-lock.json* ./
RUN npm ci && npm cache clean --force
COPY . .

RUN npm run build

# nginx state for serving content
FROM nginx
# Set working directory to nginx asset directory
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
# Copy static assets from builder stage
COPY --from=builder /app/dist .
# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]